apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-app
  template:
    metadata:
      labels:
        app: crash-app
    spec:
      containers:
      - name: main
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "echo app crash; exit 1"]
